---
name: lab-02
break: true
indent: 4
---

src/main/java/labtwo:
    CrystalBall.java:
        ConfirmFileExists
        CountSingleLineComments --language Java --count 5

writing:
    reflection.md:
        ConfirmFileExists
        CountFileWords --count 250
        CountFileParagraphs --count 4
        MatchFileFragment --fragment "{YOUR NAME HERE}" --count 0 --exact
        MatchFileFragment --fragment "TODO" --count 0 --exact
        
CountCommits --count 3
ExecuteCommand --command "gradle build"
CountCommandOutput --command "gradle run" --count 17